### PR TITLE
Fix use local auth replace session

### PR DESCRIPTION
**Pull request by su-chang**
Related issue: https://github.com/pedroslopez/whatsapp-web.js/pull/1257

### CODE REVIEW

**Comment by huan** [comment]
If you remove the MemoryCard support from a puppet, then you will not be able to restore sessions from the Wechaty framework in the future.

**Review by hcfw007 — APPROVED** [review]

**Comment by su-chang** [comment]
> If you remove the MemoryCard support from a puppet, then you will not be able to restore sessions from the Wechaty framework in the future.

I will think about how to use MemoryCard to store LocalAuth session.

For example, use MemoryCard store the LocalAuth `clientId` from Wechaty framework.

```ts
this.whatsAppClient = new WhatsApp({
  authStrategy: new LocalAuth({ clientId: 'default-client' }),
  ...
})
```

**Comment by huan** [comment]
Using MemoryCard with Wechaty/Puppet is quite easy and straightforward:

```ts
this.memory.set('clientId', clientId)
await this.memory.save()
```

Then it will be enough.

**Comment by su-chang** [comment]
Thank you for your suggestion, and MemoryCard will be back later in this pr.

**Comment by huan** [comment]
Great to know MemoryCard will be back later in this pr, and you are welcome!

**Comment by su-chang** [comment]
@huan MemoryCard back now, and do you have some other suggestions for this pr?

**Comment by huan** [comment]
Great to see that, I have no more suggestions, thank you very much.

**Pull request merged**
