### PR TITLE
change @juzibot/whatsapp-web.js to @juzi.bot/whatsapp-web.js

### PR DESCRIPTION
**Pull request by bung87**

### CODE REVIEW

**Review by guo40020 — APPROVED** [review]

**Review by wedreamer — APPROVED** [review]

**Review by huan — CHANGES_REQUESTED** [review]
Could you please explain the reason that we need to use a forked version of using the upstream module directly?

**Comment by guo40020** [comment]
> Could you please explain the reason that we need to use a forked version of the upstream module?

There are still some fatal bugs present inside `whatsapp-web.js` that could lead to bad user experience and/or high hardware usage. To speed up our development, we decided to use a forked version instead of waiting for the author to merge pull requests temperally.   
We will later merge all our changes to the original repo.

**Comment by hcfw007** [comment]
The original version has a known bug waiting to be merged. Ref: https://github.com/wechaty/puppet-whatsapp/issues/80
We want to test related functions ASAP.

**Review by hcfw007 — APPROVED** [review]

**Comment by bung87** [comment]
> Could you please explain the reason that we need to use a forked version of the upstream module?

we use `patch-package` for change dependency code before , therefore the CI package check will throw error , see https://github.com/wechaty/puppet-whatsapp/runs/4963856848?check_suite_focus=true 

I've change it dependent on [puppeteer-extra](https://github.com/berstend/puppeteer-extra) use two plugin for preventing be detected as bot.

we may change the code more , we dont want wait the author publish new version package.

**Review by huan — APPROVED** [review]
> To speed up our development, we decided to use a forked version instead of waiting

That's a great solution. Thank you very much for the explanation!

**Comment by bung87** [comment]
I dont understand why `license/cla` take so long , it takes time randomly to me.

**Pull request merged**
