### PR TITLE
Fix logout

### PR DESCRIPTION
**Pull request by su-chang**
Related issue: https://github.com/wechaty/puppet-whatsapp/issues/150

### CODE REVIEW

**Comment by bung87** [comment]
are you sure treat `disconnected` as `logout` ?

**Comment by hcfw007** [comment]
```
15:13:47 INFO PuppetWhatsApp event: "disconnected", value: "UNPAIRED"
```
for event==='disconnected' && value==='UNPAIRED', I think we can treat it as logout. Because QRCode scanning is required to login.

**Comment by su-chang** [comment]
> are you sure treat `disconnected` as `logout` ?

I think `disconnected` will match with `WAState.CONNECTED`.  I will add log in default branch when `disconnected` event happened, after we known something different then adjust this logic.

**Comment by bung87** [comment]
It sounds we don't need auto reconnected when network condition changed.

**Comment by su-chang** [comment]
> It sounds we don't need auto reconnected when network condition changed.

Nope, it depends on this issue: https://github.com/wechaty/puppet-whatsapp/issues/101

**Pull request merged**
