### PR TITLE
Fix memory card

### PR DESCRIPTION
**Pull request by hcfw007**
#336

### CODE REVIEW

**Review by su-chang — APPROVED** [review]

**Comment by hcfw007** [comment]
@huan I trined a new way to handle async test this time, is this kinda async/await style you mentioned?

**Comment by huan** [comment]
> is this kinda async/await style you mentioned?

No, it's not the async/await style. It's still the callback style. ;-p

**Comment by hcfw007** [comment]
after await puppet.start(), puppet.stop() will be called, does this affect puppet's state?

**Comment by huan** [comment]
`start`/`stop` of course will affect the state.

What's the `state` in your context?

**Comment by hcfw007** [comment]
I mean if I wrote
```
puppet.on('scan', () => {puppet.stop()}
await puppet.start()
t.ok((puppet.memory as any).payload !== undefined, 'memory is loaded')
```
will this puppet.memory.payload effected by puppet.stop()>

**Comment by huan** [comment]
I'm not sure about it.

My suggestion would be just write an unit test to confirm the behavior and make sure it's your expected.

**Pull request merged**
